In [2]:
import numpy as np
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
print("A:", A.shape)
print(A)

print("B:", B.shape)
print(B, A.shape)


A: (2, 2)
[[1 2]
 [3 4]]
B: (2, 2)
[[5 6]
 [7 8]] (2, 2)


In [14]:
C=A+B
D=A-B
E =A/B
F = A*B

print(E)
print(F)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 5 12]
 [21 32]]


In [5]:
result = A.sum()
print("result is:", result)

result is: 10


In [6]:
# Explore what is vector norm and how to calculate using numpy, Also explore where to use it

In [7]:
# Explore Eigen Calues and Eigen Vectors, and how to calculate using numpy, Also explore where to use it

In [8]:
print(A.min())

1


In [9]:
print(A.max())

4


In [12]:
P = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
# Q = np.transpose(P)
Q=P.T #transpose 2nd method
print(P)
print(Q)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [13]:
R = np.array([
    [1, 2],
    [3, 4]
])
R_inv = np.linalg.inv(R)
print(R)
print(R_inv)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [15]:
# why we use matrix dot product ->mage Processing:

In [16]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]


In [20]:
A = np.array([
    [4, 3],
    [3, 2]
])
A_inv = np.linalg.inv(A)
print(A_inv)
D = np.dot(A, A_inv)
print(D)

[[-2.  3.]
 [ 3. -4.]]
[[1. 0.]
 [0. 1.]]
